#!/usr/bin/with-contenv bash

echo "*** ACTIVATE AND INITIALIZE CHIA ***"
cd /chia
. ./activate
chia init

if chia keys show | grep -q 'There are no saved private keys'; then
    if [[ "$WALLET" == true ]] || [[ "$FARMER" == true ]]; then
        if [[ -f "/seed.key" ]]; then
            echo "*** GENERATING KEYS FROM SEED FILE ***"
            chia keys add -f /seed.key
        else
            echo "*** GENERATING NEW KEYS ***"
            chia keys generate
        fi
    fi
else
    echo "*** USING EXISTING KEYS ***"
fi

if [ $(ls -d /root/.chia/mainnet/db/blockchain_v1_mainnet.sqlite 2> /dev/null | wc -l) -eq 1 ]; then
    if [ "$UPGRADE_DB_V2" == "true" ]; then
        echo "*** UPGRADING DATABASE TO V2 ***"
        chia db upgrade
    else
        echo "*** DATABASE IS V1 ***"
    fi
    if [ "$KEEP_V1_DB" == "false" ]; then
        echo "*** CLEANING OLD DB FILE ***"
        rm /root/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
    fi
else
    echo "*** DATABASE IS V2 ***"
fi

if [ -d "/remote-ca" ] && [ "$REMOTE_HARVESTER" == "true" ]; then
    echo "*** CONFIGURING REMOTE HARVESTER ***"
    cp -a /root/.chia/mainnet/config/ssl/ca /root/.chia/mainnet/config/ssl/ca-container
    chia init -c /remote-ca
    chia configure --set-farmer-peer ${REMOTE_FARMER_IP}:${REMOTE_FARMER_PORT}
elif [ -d "/root/.chia/mainnet/config/ssl/ca-container" ]; then
    echo "*** CONFIGURING CERTS USING ORIGINAL CONTAINER CA ***"
    chia init -c /root/.chia/mainnet/config/ssl/ca-container
    chia configure --set-farmer-peer 127.0.0.1:8447
    rm -rf /root/.chia/mainnet/config/ssl/ca-container
fi

for i in $(find /root/.chia/mainnet/config/ssl/ -type f \( -name "*.key" ! -iname "*public_introducer.key" \) -printf %m -exec echo '{}' \; | cut -c 1-3); do
  if ! [ "$i" -eq 600 ]; then
    echo "*** FIXING SSL PERMISSIONS ***"
    chia init --fix-ssl-permissions
    break
  fi
done

if [ ! $(ls -d /plots/* 2> /dev/null | wc -l) -eq 0 ]; then
    echo "*** ADDED PLOT DIRECTORIES TO CONFIG ***"
    for dir in /plots/*/; do 
        chia plots add -d $dir
    done
else
    echo "*** NO PLOTS CONFIGURED ***"
fi

if [[ ! -z "${LOG_LEVEL}" ]]; then
    echo "*** SETTING CHIA LOG LEVEL TO ${LOG_LEVEL} ***"
    sed -i 's/log_level: .*/log_level: ${LOG_LEVEL}/g' /root/.chia/mainnet/config/config.yaml
fi

sed -i 's/localhost/127.0.0.1/g' /root/.chia/mainnet/config/config.yaml

echo "*** CHIA VERSION $(chia version) READY ***"